namespace ShuHai.UnityPluginProjectConfigurator.Configs
{
    /// <summary>
    ///     Provides settings for configure a certain Unity project.
    /// </summary>
    public class UnityProject
    {
        /// <summary>
        ///     Directory path of the Unity project represented by current instance.
        /// </summary>
        public string Path { get; set; }

        /// <summary>
        ///     List of C# projects that need to add to the C# solution generated by unity.
        /// </summary>
        public CSharpProject[] CSharpProjects { get; set; }

        public class CSharpProject
        {
            public string Key;

            public string DllAssetDirectory;

            public bool CreateDllAssetDirectoryIfNecessary = true;
        }
    }
}